CREATE TABLE IF NOT EXISTS chat (
    id BIGINT NOT NULL,

    PRIMARY KEY (id),
    UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    url TEXT NOT NULL,
    service_type VARCHAR NOT NULL,
    tracked_data JSONB NOT NULL,
    last_check TIMESTAMP WITH TIME ZONE,

    PRIMARY KEY (id),
    UNIQUE (id),
    UNIQUE (url)
);

CREATE TABLE IF NOT EXISTS subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    chat_id BIGINT NOT NULL,
    link_id BIGINT NOT NULL,
    alias VARCHAR(10),

    PRIMARY KEY (id),
    UNIQUE (chat_id, link_id),
    UNIQUE (chat_id, alias),
    FOREIGN KEY (chat_id) REFERENCES chat(id),
    FOREIGN KEY (link_id) REFERENCES link(id)
);
