app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jpa
  rate-limit:
    enable: true
    capacity: 10000
    relief:
      tokens: 10000
      period: "PT1H"
  notification-type: kafka


client:
  github:
    token: ${GITHUB_TOKEN}
  stackoverflow:
  bot:
    baseUrl: ${BOT_BASE_URL}
  retry:
    enable: true
    type: exponential
    base-delay-ms: 100
    retry-on-codes: [429, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 520, 521, 522, 523, 524, 525, 526]

spring:
  application:
    name: scrapper
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: "/swagger-ui"

kafka:
  bootstrapServers: ${BOOTSTRAP_SERVERS}
  clientId: scrapper
  askMode: all
  deliveryTimeout: 60s
  lingerMs: 12_000
  batchSize: 100_000
  maxInFlightPerConnection: 5
  enableIdempotence: true
  topic:
    name: scrapper
    partitions: 1
    replicas: 1

server:
  port: ${SERVER_PORT}

logging:
  config: classpath:log4j2-plain.xml
