app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

client:
  github:
    token: ${GITHUB_TOKEN}
    base-url: "datr"

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
