app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

client:
  github:
    token: ${GITHUB_TOKEN}
  stackoverflow:
  bot:
    baseUrl: http://localhost:8090

spring:
  application:
    name: scrapper
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
