app:
  telegram-token: ${BOT_TOKEN}
  threads-Per-Executor: 6
  rate-limit:
    enable: true
    capacity: 10000
    relief:
      tokens: 10000
      period: "PT1H"

client:
  scrapper:
    baseUrl: ${SCRAPPER_BASE_URL}
  retry:
    enable: true
    type: exponential
    base-delay-ms: 100
    retry-on-codes: [ 429, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 520, 521, 522, 523, 524, 525, 526 ]

kafka:
  consumer:
    bootstrapServers: ${BOOTSTRAP_SERVERS}
    groupId: linkUpdatesConsumer
    autoOffsetReset: latest
    maxPollIntervalMs: 300_000
    enableAutoCommit: false
    concurrency: 1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
    property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
