package edu.java.client.scrapper.model;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST,
    TG_CHAT_NOT_FOUND,
    TG_CHAT_ALREADY_EXIST,
    TG_CHAT_VALIDATION_FAILED,
    URL_NOT_FOUND,
    URL_ALREADY_EXIST,
    URL_VALIDATION_FAILED,
    URL_NOT_SUPPORTED,
    ALIAS_NOT_FOUND,
    ALIAS_ALREADY_EXIST,
    ALIAS_VALIDATION_FAILED
}
